### ISSUE TITLE
Can this watch arp  request?

### ISSUE THREAD

**Issue by llhhbc** [cilium/pwru#233]
Can this watch arp request and response?

**Comment by jschwinger233** [comment]
Not for now. 

This is because currently we specify `DLT_RAW` to generate cbpf insns for skb without L2 header, as explained at https://github.com/cilium/pwru/blob/8d5ffa2209ed12417cd1637dc453f937ed786d4f/internal/libpcap/compile.go#L33-L41

However it seems possible to make improvement for L2 skb. The rough idea is something like:

```c
if (skb->mac_len == 0) {
    data_start = skb->mac_header;
    pcap_filter_l2(data_start, data_end);
} else {
    data_start = skb->network_header;
    pcap_filter_l3(data_start, data_end);
}
```

We can compile ebpf filter insns for both situations and inject them into `pcap_filter_l2` and `pcap_filter_l3` correspondingly.

**Comment by llhhbc** [comment]
@jschwinger233 Can this will be merged to master?

**Comment by llhhbc** [comment]
Thanks very much.
