### ISSUE TITLE
[Question] How are each of the kprobe programs getting access to the `sk_buff`

### ISSUE THREAD

**Issue by nitishm** [cilium/pwru#33]
I noticed in the section of the code below, that there are 5 kprobe programs and each of them are reading the sk_buff for the intercepted data from different params 1-5 respectively. 

The question is, what is the significance of `PT_REG_PARMx` and also why do we need 5 kprobe programs?

https://github.com/cilium/pwru/blob/master/bpf/kprobe_pwru.c#L359-L392

**Comment by pchaigno** [comment]
pwru attaches to kernel functions that take a `sk_buff` as a parameter. Depending on which parameter hold the `sk_buff`, a different kprobe program needs to be used. For example, if the `sk_buff` is the second parameter, `kprobe/skb-2` will be used since `PT_REGS_PARM2` retrieves the second parameter from the CPU registers. If it's the fourth parameter, then `kprobe/skb-4` is used, etc.

**Comment by nitishm** [comment]
> pwru attaches to kernel functions that take a `sk_buff` as a parameter. Depending on which parameter hold the `sk_buff`, a different kprobe program needs to be used. For example, if the `sk_buff` is the second parameter, `kprobe/skb-2` will be used since `PT_REGS_PARM2` retrieves the second parameter from the CPU registers. If it's the fourth parameter, then `kprobe/skb-4` is used, etc.

Makes sense. However, I am having trouble understanding some parts of the userspace code. How do you decide what these functions are?

**Comment by brb** [comment]
It extracts from the kernel BTF: https://github.com/cilium/pwru/blob/master/internal/pwru/utils.go#L15
