### ISSUE TITLE
Not able to run pwru with --filter-dst-port option due to OOM

### ISSUE THREAD

**Issue by achilles-git** [cilium/pwru#45]
```
[vagrant@fedora ~]$ sudo ./pwru --filter-dst-port=11211
2022/01/07 03:50:20 Attaching kprobes...
473 / 1333 [-----------------------------------------------   35.48% 17 p/s
Killed
```

i am able to run pwru just like sudo ./pwru 
but not able to apply any filters

**Comment by achilles-git** [comment]
it was a typo
--filter-dst-port 11211 instead of --filter-dst-port=11211

**Comment by brb** [comment]
Could you show `dmesg` output?

**Comment by achilles-git** [comment]
```
[   69.777400] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-4.scope,task=pwru,pid=1624,uid=0
[   69.778302] Out of memory: Killed process 1624 (pwru) total-vm:777540kB, anon-rss:70648kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:232kB oom_score_adj:0
[   69.784610] oom_reaper: reaped process 1624 (pwru), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```


Ohk
i have 2GB memory and no application is running
is that not sufficient  ??

**Comment by brb** [comment]
I remember @ti-mo mentioning somewhere that `cilium/ebpf` kprobe orchestration code consumes a lot of mem per kprobe. @ti-mo?

**Comment by ti-mo** [comment]
> kprobe orchestration code consumes a lot of mem per kprobe

Not sure where this is coming from. I mentioned parsing vmlinux BTF makes enormous amounts of allocations in its current state (around 500MB on my machine), which might cause trouble running pwru on nodes with smaller memory budgets.

**Comment by YutaroHayakawa** [comment]
@achilles-git Do you happen to have many messages from audit subsystem in dmesg? In that case, what happens when you try with `setenforce Permissive` (if the situation allows)?

===
When SELinux is enabled, in some cases, an audit message (https://bugzilla.redhat.com/show_bug.cgi?id=1955585) is generated per eBPF program invocation. Since pwru attaches the BPF program for hundreds or thousands of functions, many messages are generated in a very short time.

As a result, auditd cannot catch up to the speed and the message will be queued up to the backlog memory inside the kernel. Then, OOM killer works. I saw this issue in [ipftrace2](https://github.com/YutaroHayakawa/ipftrace2) which internally does very similar thing as pwru.

**Comment by brb** [comment]
@YutaroHayakawa Thanks for the investigation! Mind opening the PR to add your findings to KNOWN_ISSUES.md (the file needs to be created)?

**Comment by YutaroHayakawa** [comment]
Created the one.

https://github.com/cilium/pwru/pull/52
